swagger: "2.0"
info:
  description: "HCM API documentation."
  version: "1.31"
  title: "HCM"
host: "admin.int.healthcaremgr.net"
basePath: "/common/Common"
schemes:
- "https"
- "http"
paths: 
  /get_take_access_lock:
    post:
      summary: "gets or takes the access lock of object/object id"
      description: ""
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "request_data"
        description: ""
        required: true
        schema:
          type: object
          properties:
            data:
              type: "object"
              properties:
                object_type:
                  type: string
                object_id:
                  type: integer
                check_only:
                  type: boolean
            token: 
              type: string
              example: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.IlByYW5hdi5HYWpqYXJAYW1waW9uLmNvbS5hdTIwMjAtMTAtMjAgMTA6MDE6MDIi
      responses:
        "200":
          description: "successful operation"
          schema:
            properties:
              msg:
                type: string
              status:
                type: boolean 
        "500":
          description: "Server error"
  /remove_access_lock:
    post:
      summary: "Removes object level lock"
      description: ""
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "request_data"
        description: ""
        required: true
        schema:
          type: object
          properties:
            data:
              type: "object"
              properties:
                object_type:
                  type: string
                object_id:
                  type: integer
            token: 
              type: string
              example: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.IlByYW5hdi5HYWpqYXJAYW1waW9uLmNvbS5hdTIwMjAtMTAtMjAgMTA6MDE6MDIi
      responses:
        "200":
          description: "successful operation"
          schema:
            properties:
              msg:
                type: string
              status:
                type: boolean 
        "500":
          description: "Server error"
definitions:
  time:
    type: string
    pattern: /([0-9]{2}):(?:[0-9]{2}) ([(AM)(PM)])/
    example: "HH:MM AM/PM" 
  date:
    type: string
    pattern: /([0-9]{4})-(?:[0-9]{2})-([0-9]{2})/
    example: "2019-05-17"
  datetime:
    type: string
    pattern: /([0-9]{4})-(?:[0-9]{2})-([0-9]{2}) (\d{2}):(\d{2}):(\d{2})/
    example: "2019-05-17 00:00:00"