---
swagger: "2.0"
info:
  description: HCM API documentation.
  version: 1.0.0
  title: HCM
host: virtserver.swaggerhub.com
basePath: /OPT7/DocumentType/1.0.0
tags:
- name: Document Type - Edit
  description: Edit document type
schemes:
- https
- http
paths:
  /get_document_data_by_id:
    post:
      tags:
      - Document Type - Edit
      summary: Edit document type
      description: ""
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: request_data
        description: ""
        required: true
        schema:
          $ref: '#/definitions/request_data'
      responses:
        "200":
          description: Edit Document Type
          schema:
            $ref: '#/definitions/inline_response_200'
        "500":
          description: Server error
      security:
      - api_key: []
securityDefinitions:
  api_key:
    type: apiKey
    name: pin
    in: query
definitions:
  datetime:
    type: string
    pattern: /([0-9]{4})-(?:[0-9]{2})-([0-9]{2}) (\d{2}):(\d{2}):(\d{2})/
    format: date-time
    example: 2019-05-17 00:00:00
  get_document_data_by_id_data_doc_related_to_selection:
    type: object
    properties:
      label:
        type: string
      id:
        type: integer
  get_document_data_by_id_data:
    type: object
    properties:
      title:
        type: string
      issue_date_mandatory:
        type: boolean
        example: false
      expire_date_mandatory:
        type: boolean
        example: false
      reference_number_mandatory:
        type: boolean
        example: false
      active:
        type: boolean
        example: false
      doc_related_to_selection:
        type: array
        items:
          $ref: '#/definitions/get_document_data_by_id_data_doc_related_to_selection'
      document_id:
        type: integer
      doc_category:
        type: integer
        example: 1
  request_data:
    type: object
    properties:
      token:
        type: string
      data:
        $ref: '#/definitions/get_document_data_by_id_data'
  inline_response_200_data:
    type: object
    properties:
      status:
        type: boolean
      msg:
        type: string
        example: Document Deleted Successfully.
  inline_response_200:
    type: object
    properties:
      data:
        $ref: '#/definitions/inline_response_200_data'
