swagger: "2.0"
info:
  description: "HCM API documentation."
  version: "1.27"
  title: "HCM"
host: "admin.int.healthcaremgr.net"
basePath: "/admin/ProcessBuilder"
schemes:
- "https"
- "http"
paths:
  /get_process_list:
    post:
      summary: "Get List of Process Builder Events"
      description: ""
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "request_data"
        description: ""
        required: true
        schema:
          type: object
          properties:
            data:
              type: "object"
              properties:
                filtered: 
                  type: object
                  properties:
                    filter_status:
                      type: string
                page: 
                  type: integer
                pageSize: 
                  type: string
                sorted: 
                  type: array
                  items:
                    type: object
      security:
        - api_key: []
      responses:
        "200":
          description: "List of Process Builder Events"
          schema:
            type: object
            properties:
              data:
                type: "object"
                properties:
                  id: 
                    type: integer
                  name: 
                    type: string
                  description: 
                    type: string
                  created_by: 
                    type: string
              status:
                  type: boolean
              message:
                type: string
        "500":
          description: "Server error"
securityDefinitions:
  api_key:
    type: "apiKey"
    name: "pin"
    in: "query"
definitions:
  datetime:
    type: string
    format: date-time
    pattern: /([0-9]{4})-(?:[0-9]{2})-([0-9]{2}) (\d{2}):(\d{2}):(\d{2})/
    example: "2019-05-17 00:00:00"