swagger: "2.0"
info:
  description: "HCM API documentation."
  version: "1.22"
  title: "HCM"
host: "admin.int.healthcaremgr.net"
basePath: "/sales/ListViewControls"
schemes:
- "https"
- "http"
paths:
  /get_list_view_controls_by_default_pinned:
    post:
      summary: "Get default pinned filter data by related type"
      description: ""
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "request_data"
        description: ""
        required: true
        schema:
          type: object
          properties:
            data:
              type: "object"
              properties:
                related_type: 
                  type: integer
                  example: 1
      security:
        - api_key: []
      responses:
        "200":
          description: "List of Roles"
          schema:
            type: object
            properties:
              data:
                type: object
                properties:
                  created_by: 
                    type: integer
                    example: 11
                  filter_data: 
                    type: string
                    example: '"[{"select_filter_field":"ID","select_filter_field_val":"contact_code","select_filter_operator":"equals","select_filter_operator_sym":"=","select_filter_value":"s","selectedfield_sort":"1"}]"'
                  filter_logic: 
                    type: string
                    example: '1 AND 2'
                  filter_operand: 
                    type: string
                    example: '0'
                  label: 
                    type: string
                    example: 'Public list'
                  pinned_id: 
                    type: integer
                    example: 21
                  user_view_by: 
                    type: string
                    example: 2
                  value: 
                    type: string
                    example: 32
              isOwnList: 
                type: boolean    
              status: 
                type: boolean
        "500":
          description: "Server error"
securityDefinitions:
  api_key:
    type: "apiKey"
    name: "pin"
    in: "query"