swagger: "2.0"
info:
  description: "HCM API documentation."
  version: "1.22"
  title: "HCM"
host: "admin.int.healthcaremgr.net"
basePath: "item/Goals/get_tracked_goals_by_participant"
schemes:
- "https"
- "http"
paths:
  /get_tracked_goals_by_participant:
    post:
      summary: "get goals tracked from shift by participant ID"
      description: ""
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "request_data"
        description: ""
        required: true
        schema:
          type: object
          properties:
            data:
              type: "object"
              properties:
                filtered: 
                  type: object
                  example: {filter_status: "all"}
                page: 
                  type: integer
                  example: 0
                pageSize: 
                  type: integer
                  example: 20
                participant_id:
                   type: integer
                   example: 20
      security:
        - api_key: []
      responses:
        "200":
          description: "get goals tracked from shift by participant ID"
          schema:
            type: array
            properties:
              data:
                type: array
        "500":
          description: "Server error"
securityDefinitions:
  api_key:
    type: "apiKey"
    name: "pin"
    in: "query"