swagger: "2.0"
info:
  description: "HCM API documentation."
  version: "1.22"
  title: "HCM"
host: "admin.int.healthcaremgr.net"
basePath: "/member/MemberRole"
schemes:
- "https"
- "http"
paths:
  /get_member_roles:
    post:
      summary: "List all Roles"
      description: ""
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "request_data"
        description: ""
        required: true
        schema:
          type: object
          properties:
            data:
              type: "object"
              properties:
                id:
                  type: "integer"
                limit:
                  type: "integer"
      security:
        - api_key: []
      responses:
        "200":
          description: "List of Roles"
          schema:
            type: object
            properties:
              levels:
                type: array
                items:
                  $ref: "#/definitions/tupple"
              member:
                type: object
                properties:
                  member_id:
                    type: integer
                  member_name:
                    type: string
              pay_points:
                type: array
                items:
                  type: object
                  properties:
                    label: 
                     type: string
                    value: 
                     type: integer
              roles:
                type: array
                items:
                  type: object
                  properties:
                    level: 
                     type: integer
                    member_id: 
                     type: integer
                    member_role_id: 
                     type: integer
                    pay_point: 
                     type: integer
                    role_end_time:
                      $ref: "#/definitions/datetime"
                    role_id: 
                     type: integer
                    role_name: 
                     type: string
                    role_start_time: 
                      $ref: "#/definitions/datetime"
              status:
                type: boolean
        "500":
          description: "Server error"
  /get_member_role_details:
    post:
      summary: "Get Details of a Member Role"
      description: ""
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "request_data"
        description: ""
        required: true
        schema:
          type: object
          properties:
            data:
              type: "object"
              properties:
                id:
                  type: integer
      security:
        - api_key: []
      responses:
        "200":
          description: "successful operation"
          schema:
            properties:
              data:
                $ref: "#/definitions/member"
              status:
                type: boolean 
        "500":
          description: "Server error"
  /get_pay_point_options:
    post:
      summary: "Returns Array of Pay Point from Refrence Data"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "request_data"
        description: ""
        required: true
        schema:
          type: object
          properties:
            data:
              type: object
            pin:
              type: string
            token: 
              type: string
      responses:
        200:
          description: "OK"
          schema:
            type: array
            items:
              $ref: "#/definitions/tupple"
  /get_level_options:
    post:
      summary: "Returns Array of Levels from Refrence Data"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "request_data"
        description: ""
        required: true
        schema:
          type: object
          properties:
            data:
              type: object
            pin:
              type: string
            token: 
              type: string
      responses:
        200:
          description: "OK"
          schema:
            type: array
            items:
              $ref: "#/definitions/tupple"
  /get_time_slots_half_hour:
    post:
      summary: "Returns Array of 30 Minutes Time Slots"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "request_data"
        description: ""
        required: true
        schema:
          type: object
          properties:
            data:
              type: object
            pin:
              type: string
            token: 
              type: string
      responses:
        200:
          description: "OK"
          schema:
            type: array
            items:
              $ref: "#/definitions/tupple"
  /archive_member_role:
    post: 
      summary: "Delete a Member Role"
      parameters:
      - in: "body"
        name: "request_data"
        description: ""
        required: true
        schema:
          type: object
          properties:
            data:
              type: "object"
              properties:
                id:
                  type: "string"
            pin:
              type: "string"
            token:
              type: "string"
      responses:
        200:
          description: "OK"
          schema:
            type: object
            properties:
              msg:
                type: string
              status:
                type: boolean
    
securityDefinitions:
  api_key:
    type: "apiKey"
    name: "pin"
    in: "query"
definitions:
  date:
    type: string
    format: date
    pattern: /([0-9]{4})-(?:[0-9]{2})-([0-9]{2})/
    example: "2019-05-17"
  datetime:
    type: string
    format: date-time
    pattern: /([0-9]{4})-(?:[0-9]{2})-([0-9]{2}) (\d{2}):(\d{2}):(\d{2})/
    example: "2019-05-17 00:00:00"
  member:
    type: object
    properties:
      level: 
        type: integer
      member_id: 
        type: integer
      member_name: 
        type: string
      member_role_id: 
        type: integer
      pay_point: 
        type: integer
      role_end_time: 
        $ref: "#/definitions/datetime"
      role_id: 
        type: integer
      role_name: 
        type: string
      role_start_time: 
        $ref: "#/definitions/datetime"
  tupple:
    type: object
    properties:
      label:
        type: string
      value:
        type: integer