swagger: "2.0"
info:
  description: "HCM API documentation."
  version: "1.25"
  title: "HCM"
host: "admin.int.healthcaremgr.net"
basePath: "/item/participant"
schemes:
- "https"
- "http"
paths:
  /get_participant_member_ref_data:
    post:
      summary: "Fetching list of statuses (reference list)"
      description: ""
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "request_data"
        description: ""
        required: true
        schema:
          type: object
          properties:
            data:
              type: "object"
              properties:
                token: 
                  type: string
                  example: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.IlByYW5hdi5HYWpqYXJAYW1waW9uLmNvbS5hdTIwMjAtMTAtMjAgMTA6MDE6MDIi
      responses:
        "200":
          description: "List of statuses"
          schema:
            type: object
            properties:
              data:
                type: array
                items:
                  $ref: "#/definitions/tupple"
        "500":
          description: "Server error"
  /get_participant_member_list:
    post:
      summary: "List all participant members"
      description: ""
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "request_data"
        description: ""
        required: true
        schema:
          type: object
          properties:
            data:
              type: "object"
              properties:
                page:
                  type: integer
                pageSize:
                  type: integer
                participant_id:
                  type: integer
                sorted:
                  type: object
                  properties:
                    column:
                      type: string
                    value:
                      type: string
            token: 
              type: string
              example: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.IlByYW5hdi5HYWpqYXJAYW1waW9uLmNvbS5hdTIwMjAtMTAtMjAgMTA6MDE6MDIi
      responses:
        "200":
          description: "List of participant members"
          schema:
            type: object
            properties:
              data:
                type: array
                items:
                  $ref: "#/definitions/participant_members"
              status:
                type: boolean
        "500":
          description: "Server error"
  /archive_participant_member:
    post: 
      summary: "Delete a participant member"
      parameters:
      - in: "body"
        name: "request_data"
        description: ""
        required: true
        schema:
          type: object
          properties:
            data:
              type: "object"
              properties:
                id:
                  type: "integer"
            token: 
              type: string
              example: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.IlByYW5hdi5HYWpqYXJAYW1waW9uLmNvbS5hdTIwMjAtMTAtMjAgMTA6MDE6MDIi
      responses:
        200:
          description: "OK"
          schema:
            type: object
            properties:
              msg:
                type: string
              status:
                type: boolean
  /assign_participant_members:
    post:
      summary: "Creating or updating a participant member"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "request_data"
        description: ""
        required: true
        schema:
          type: object
          properties:
            data:
              type: object
              properties:
                participant_id: 
                  type: integer
                participant_members: 
                  type: array
                  items:
                    type: integer
                  properties:
                    member_obj:
                      type: object
                      properties:
                        label:
                          type: string
                        value:
                          type: integer
                    status: 
                      type: integer
            token: 
              type: string
              example: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.IlByYW5hdi5HYWpqYXJAYW1waW9uLmNvbS5hdTIwMjAtMTAtMjAgMTA6MDE6MDIi
      responses:
        "200":
          description: "Successful creating/updating of participant members"
          schema:
            type: object
            properties:
              msg: 
                type: string
                example: 'Participant members have been assigned successfully'
              status: 
                type: boolean
                example: true
        "500":
          description: "Server error"
definitions:
  date:
    type: string
    format: date
    pattern: /([0-9]{4})-(?:[0-9]{2})-([0-9]{2})/
    example: "2019-05-17"
  datetime:
    type: string
    format: date-time
    pattern: /([0-9]{4})-(?:[0-9]{2})-([0-9]{2}) (\d{2}):(\d{2}):(\d{2})/
    example: "2019-05-17 00:00:00"
  participant_members:
    type: object
    properties:
      id: 
        type: integer
      member_id: 
        type: integer
      fullname: 
        type: string
      participant_id: 
        type: integer
      status: 
        type: integer
      created: 
        $ref: "#/definitions/datetime"
      status_label: 
        type: string
      actions:
        type: string
  tupple:
    type: object
    properties:
      label:
        type: string
      value:
        type: integer