swagger: "2.0"
info:
  description: "HCM API documentation."
  version: "1.32"
  title: "HCM"
host: "admin.int.healthcaremgr.net"
basePath: "/common/Resource"
schemes:
- "https"
- "http"
paths: 
  /get_level_options:
    post:
      summary: "Fetching the pay level options"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "request_data"
        description: ""
        required: true
        schema:
          type: object
          properties:
            token: 
              type: string
              example: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.IlByYW5hdi5HYWpqYXJAYW1waW9uLmNvbS5hdTIwMjAtMTAtMjAgMTA6MDE6MDIi
      responses:
        200:
          description: "OK"
          schema:
            type: array
            items:
              $ref: "#/definitions/tupple"
        "500":
          description: "Server error"
  /get_pay_point_options:
    post:
      summary: "Fetching the pay point options"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "request_data"
        description: ""
        required: true
        schema:
          type: object
          properties:
            token: 
              type: string
              example: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.IlByYW5hdi5HYWpqYXJAYW1waW9uLmNvbS5hdTIwMjAtMTAtMjAgMTA6MDE6MDIi
      responses:
        200:
          description: "OK"
          schema:
            type: array
            items:
              $ref: "#/definitions/tupple"
        "500":
          description: "Server error"
  /get_employment_type_options:
    post:
      summary: "Fetching the employment type options"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "request_data"
        description: ""
        required: true
        schema:
          type: object
          properties:
            token: 
              type: string
              example: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.IlByYW5hdi5HYWpqYXJAYW1waW9uLmNvbS5hdTIwMjAtMTAtMjAgMTA6MDE6MDIi
      responses:
        200:
          description: "OK"
          schema:
            type: array
            items:
              $ref: "#/definitions/tupple"
        "500":
          description: "Server error"
definitions:
  date:
    type: string
    format: date
    pattern: /([0-9]{4})-(?:[0-9]{2})-([0-9]{2})/
    example: "2019-05-17"
  datetime:
    type: string
    format: date-time
    pattern: /([0-9]{4})-(?:[0-9]{2})-([0-9]{2}) (\d{2}):(\d{2}):(\d{2})/
    example: "2019-05-17 00:00:00"
  tupple:
    type: object
    properties:
      label:
        type: string
      value:
        type: integer