swagger: "2.0"
info:
  description: HCM API documentation.
  version: 1.0.0
  title: HCM
host: "admin.int.healthcaremgr.net"
basePath: "/admin/api/"
tags:
- name: Save Viewed Log
  description: Save Viewed Log
schemes:
- https
- http
paths:
  /save_viewed_log:
    post:
      tags:
      - Save Viewed Log
      summary: ""
      description: ""
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: request_data
        description: ""
        required: true
        schema:
          $ref: '#/definitions/request_data_1'
      responses:
        "200":
          description: Save Viewed Log
          schema:
            $ref: '#/definitions/inline_response_200_1'
        "500":
          description: Server error
      security:
      - api_key: []
securityDefinitions:
  api_key:
    type: apiKey
    name: pin
    in: query
definitions:
  datetime:
    type: string
    pattern: /([0-9]{4})-(?:[0-9]{2})-([0-9]{2}) (\d{2}):(\d{2}):(\d{2})/
    format: date-time
    example: 2019-05-17 00:00:00
  save_viewed_log:
    type: object
    properties:
      entity_type:
        type: string
        example: 'application|applicant|lead|opportunity|service_agreement'
      entity_id:
        type: integer
        example: 'refrence of entity_type unique id'
  request_data_1:
    type: object
    properties:
      token:
        type: string
      data:
        $ref: '#/definitions/save_viewed_log'
  inline_response_200_1:
    type: object
    properties:
      status:
        type: boolean
