swagger: "2.0"
info:
  description: "HCM API documentation."
  version: "1.22"
  title: "HCM"
host: "admin.int.healthcaremgr.net"
basePath: "/recruitment/OnlineAssessment"
schemes:
- "https"
- "http"
paths:
  /assessment_reminder_mail:
    post:
      summary: "To sends the Assessment Reminder if candidate haven't accessed it in 24hrs from receiving"
      description: ""
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "request_data"
        description: ""
        required: true
        schema:
          type: object
          properties:
            data:
              type: "object"
              properties:
                expire_time: 
                  type: string
                  example: '-1 days'
                  
      security:
        - api_key: []
      responses:
        "200":
          description: "To sends the Assessment Reminder if candidate haven't accessed it in 24hrs from receiving"
          schema:
            type: object
            properties:
              data:
                type: object
                properties:
                    msg: 
                     type: string
                     example: 'Reminder Sent Successfully/Nothing to send for reminder!'
                    status: 
                     type: boolean
                    data: 
                     type: object
                     example: '[b23327cc-0924-31b3-4bcf-99ce, ya23327cc-0924-31b3-4bcf-99ce]'
                    
                     
        "500":
          description: "Server error"
securityDefinitions:
  api_key:
    type: "apiKey"
    name: "pin"
    in: "query"