swagger: "2.0"
info:
  description: "HCM API documentation."
  version: "1.26"
  title: "HCM"
host: "admin.int.healthcaremgr.net"
basePath: "/admin/Settings"
schemes:
- "https"
- "http"
paths: 
  /get_general_settings:
    post:
      summary: "Fetching the application general settings"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "request_data"
        description: ""
        required: true
        schema:
          type: object
          properties:
            data:
              type: object
              properties:
                id: 
                  type: integer
            token: 
              type: string
              example: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.IlByYW5hdi5HYWpqYXJAYW1waW9uLmNvbS5hdTIwMjAtMTAtMjAgMTA6MDE6MDIi
      responses:
        "200":
          description: "Successful fetching of application general settings"
          schema:
            type: object
            properties:
              data:
                type: array
                items:
                  gap_between_shifts:
                    type: integer
                  google_travel_duration:
                    type: integer
                  overtime_allowed:
                    type: integer
                  privacy_idea_otp_enabled:
                    type: integer
              status: 
                type: boolean
                example: true
        "500":
          description: "Server error"
  /save_general_settings:
    post:
      summary: "Saving the application general settings"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "request_data"
        description: ""
        required: true
        schema:
          type: object
          properties:
            data:
              type: object
              properties:
                gap_between_shifts:
                    type: integer
                google_travel_duration:
                  type: integer
                overtime_allowed:
                  type: integer
                privacy_idea_otp_enabled:
                  type: integer
            token: 
              type: string
              example: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.IlByYW5hdi5HYWpqYXJAYW1waW9uLmNvbS5hdTIwMjAtMTAtMjAgMTA6MDE6MDIi
      responses:
        "200":
          description: "Successful saving of the application general settings"
          schema:
            type: object
            properties:
              msg: 
                type: string
                example: 'Settings successfully saved'
              status: 
                type: boolean
                example: true
        "500":
          description: "Server error"
definitions:
  date:
    type: string
    format: date
    pattern: /([0-9]{4})-(?:[0-9]{2})-([0-9]{2})/
    example: "2019-05-17"
  datetime:
    type: string
    format: date-time
    pattern: /([0-9]{4})-(?:[0-9]{2})-([0-9]{2}) (\d{2}):(\d{2}):(\d{2})/
    example: "2019-05-17 00:00:00"