swagger: "2.0"
info:
  description: "HCM API documentation."
  version: "1.22"
  title: "HCM"
host: "admin.int.healthcaremgr.net"
basePath: "/recruitment/Recruitment_member"
schemes:
- "https"
- "http"
paths:
  /update_applicant_quiz_open_status:
    post:
      summary: "Updating the quiz submit status"
      description: ""
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "request_data"
        description: ""
        required: true
        schema:
          type: object
          properties:
            data:
              type: "object"
              properties:
                applicant_id: 
                  type: integer
                  example: 1
                task_applicant_id: 
                  type: integer
                  example: 2
      security:
        - api_key: []
      responses:
        "200":
          description: "Creating the list view control"
          schema:
            type: object
            properties:
              data:
                type: object
                properties:
                    msg: 
                     type: string
                     example: 'Quiz status updated successfully.'
                    status: 
                     type: boolean
        "500":
          description: "Server error"
securityDefinitions:
  api_key:
    type: "apiKey"
    name: "pin"
    in: "query"