swagger: "2.0"
info:
  description: "HCM API documentation."
  version: "1.22"
  title: "HCM"
host: "admin.int.healthcaremgr.net"
basePath: "/member/MemberRole"
schemes:
- "https"
- "http"
paths:
  /update_member:
    post:
      summary: "Update Member Details by Applicant ID"
      description: ""
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "request_data"
        description: ""
        required: true
        schema:
          type: object
          properties:
            data:
              type: "object"
              properties:
                member_id: 
                  type: integer
                  example: 11
                applicant_id: 
                  type: integer
                  example: 101
                created_by: 
                  type: integer
                  example: 20
                hours_per_week:
                   type: string
                   example: 20
                max_dis_to_travel:
                   type: string
                   example: 20
                mem_experience:
                   type: string
                   example: 20
                updated_by:
                   type: integer
                   example: 20
                account_person: 
                   type: object
                   properties:
                     label: 
                      type: string
                     id:
                      type: integer
                language_selection:
                   type: object
                   properties:
                     label: 
                      type: string
                      example: "Latin" 
                     id:
                      type: integer
                      example: 19 
                like_selection:
                   type: object
                   properties:
                     label: 
                      type: string
                      example: "Acting" 
                     id:
                      type: integer
                      example: 11 
                transport_selection:
                   type: object
                   properties:
                     label: 
                      type: string
                      example: "Public Transport" 
                     id:
                      type: integer
                      example: 12 
      security:
        - api_key: []
      responses:
        "200":
          description: "Update Member Details by Applicant ID"
          schema:
            type: object
            properties:
              data:
                type: object
                properties:
                    msg: 
                     type: string
                     example: 'Member has been updated successfully.'
                    status: 
                     type: boolean
        "500":
          description: "Server error"
securityDefinitions:
  api_key:
    type: "apiKey"
    name: "pin"
    in: "query"