<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreateFinanceStatementTable extends Migration {

    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up() {
        Schema::create('tbl_finance_statement', function (Blueprint $table) {
            $table->increments('id');
            $table->string('statement_number', 30)->nullable()->comment('auto generated by trigger');
            $table->dateTime('from_date')->comment('statement from date');
            $table->dateTime('to_date')->comment('statement to date');
            $table->dateTime('issue_date')->comment('statement issue date');
            $table->dateTime('due_date')->comment('statement due date');
            $table->string('statement_notes', 300);
            $table->timestamp('updated')->default(DB::raw('CURRENT_TIMESTAMP'));
            $table->dateTime('created')->default('0000-00-00 00:00:00');
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down() {
        Schema::dropIfExists('tbl_finance_statement');
    }

}
